development:
  reply: "no-reply@example.com"
  host: "example.com"
  subject: "[Example] "
  smtp:
    address: "smtp.gmail.com"
    port: 587
    domain: "gmail.com"
    authentication: "plain"
    user_name: "example@example.com"
    password: "0975519929"
    enable_starttls_auto: true
test:
  reply: "no-reply@example.com"
  host: "example.com"
  subject: "[Example] "
production:
  reply: "jimmy@gogojimmy.net"
  host: "gogojimmy.net"
  subject: "[Notification] "
  smtp:
    address: "smtp.gmail.com"
    port: 587
    domain: "gmail.com"
    authentication: "plain"
    user_name: "jimmy@gogojimmy.net"
    password: "0975519929"
    enable_starttls_auto: true
